### PR TITLE
Updates for compatibility with tusd 1.x

### PR DESCRIPTION
**Pull request by acj**
The 1.x release of tusd introduced a new `Lock` interface that's separate from `Locker`. This PR introduces a `Lock` type that conforms to the upstream interface and makes the locker compatible with newer versions of tusd. I tried to use a light touch on everything else so that the breaking changes are few.

Still testing, but feedback is welcome.

Ohai @chen-anders :) 👋

### CODE REVIEW

**Comment by chen-anders** [comment]
Changes look good, but please rebase so we know that everything still works for sure :)

**Comment by acj** [comment]
Huh. I rebased after you merged the new CI workflow, but it didn't run. I can try again. If that doesn't work, maybe we need a `pull_request` line in the workflow?

**Comment by chen-anders** [comment]
🤔  oh interesting. let me add that then

**Comment by chen-anders** [comment]
Just added pull_request events to trigger tests: https://github.com/chen-anders/tusd-dynamo-locker/commit/31a7a3947fcb1f0f33dddd7a9958de2aea5b9a19 

It just occurred to me that draft PRs might not trigger test runs.

**Review by chen-anders — APPROVED** [review]

**Comment by acj** [comment]
I'll post again once I've had a chance to properly test this on our end. There was a bit of yak shaving to do before the actual tusd upgrade.

**Comment by acj** [comment]
Looks good on my end 👍

**Pull request merged**
